// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using FoodDiary2;

namespace FoodDiary2.iOS.Controller
{
	public partial class FDGoalsVC : UIViewController
	{
		public FDGoalsVC (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			tableView.Source = new FDGoalsDataSource ();
			tableView.ReloadData ();

		}

		partial void menuBtnTapped (UIBarButtonItem sender)
		{
			AppDelegate.SidebarController.ToggleMenu ();		
		}

		partial void btnShowDatePickerTapped (UIKit.UIButton sender)
		{
			
		}

		partial void cancelAddTargetBtnTapped (UIKit.UIButton sender)
		{
			throw new System.NotImplementedException ();
		}

		partial void btnDoneToolbarTapped (UIKit.UIBarButtonItem sender)
		{
			
		}


	}
}
