//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodJournal.WinPhone.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoodJournal.WinPhone.Common.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AcceptNew {
            get {
                return ResourceManager.GetString("AcceptNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a serving size.
        /// </summary>
        public static string AddServingSize {
            get {
                return ResourceManager.GetString("AddServingSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to launcher.
        /// </summary>
        public static string AddToLauncher {
            get {
                return ResourceManager.GetString("AddToLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisement.
        /// </summary>
        public static string Advertisement {
            get {
                return ResourceManager.GetString("Advertisement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This task updates the Live Tile for the Food Diary..
        /// </summary>
        public static string AgentDescription {
            get {
                return ResourceManager.GetString("AgentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have disabled the Live Tile application in phone settings..
        /// </summary>
        public static string AgentDisabled {
            get {
                return ResourceManager.GetString("AgentDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOOD DIARY.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Diary.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg.
        /// </summary>
        public static string Avg {
            get {
                return ResourceManager.GetString("Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buy now.
        /// </summary>
        public static string BuyNow {
            get {
                return ResourceManager.GetString("BuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter weight.
        /// </summary>
        public static string CantCalculateNutrition {
            get {
                return ResourceManager.GetString("CantCalculateNutrition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        public static string CommaListSeparater {
            get {
                return ResourceManager.GetString("CommaListSeparater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common items.
        /// </summary>
        public static string CommonItems {
            get {
                return ResourceManager.GetString("CommonItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common breakfast items.
        /// </summary>
        public static string CommonItems_Breakfast {
            get {
                return ResourceManager.GetString("CommonItems_Breakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common dinner items.
        /// </summary>
        public static string CommonItems_Dinner {
            get {
                return ResourceManager.GetString("CommonItems_Dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common lunch items.
        /// </summary>
        public static string CommonItems_Lunch {
            get {
                return ResourceManager.GetString("CommonItems_Lunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common snack items.
        /// </summary>
        public static string CommonItems_Snack {
            get {
                return ResourceManager.GetString("CommonItems_Snack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common afternoon items.
        /// </summary>
        public static string CommonItems_SnackAfternoon {
            get {
                return ResourceManager.GetString("CommonItems_SnackAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common early afternoon items.
        /// </summary>
        public static string CommonItems_SnackEarlyAfternoon {
            get {
                return ResourceManager.GetString("CommonItems_SnackEarlyAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common evening items.
        /// </summary>
        public static string CommonItems_SnackEvening {
            get {
                return ResourceManager.GetString("CommonItems_SnackEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common midnight items.
        /// </summary>
        public static string CommonItems_SnackMidnight {
            get {
                return ResourceManager.GetString("CommonItems_SnackMidnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common morning items.
        /// </summary>
        public static string CommonItems_SnackMorning {
            get {
                return ResourceManager.GetString("CommonItems_SnackMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100 g|1 oz=28 g|Teaspoon=4.5 g|Tablespoon=12 g|1 serving=28 g|Piece=14 g|Slice=12 g|1 cup=237 g.
        /// </summary>
        public static string CommonServingSizes {
            get {
                return ResourceManager.GetString("CommonServingSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooking time.
        /// </summary>
        public static string CookingTime {
            get {
                return ResourceManager.GetString("CookingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy from similar item.
        /// </summary>
        public static string CopyFromSimilarItem {
            get {
                return ResourceManager.GetString("CopyFromSimilarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string DatabaseCulture {
            get {
                return ResourceManager.GetString("DatabaseCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete entry.
        /// </summary>
        public static string DeleteEntry {
            get {
                return ResourceManager.GetString("DeleteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address.
        /// </summary>
        public static string EmailReport_Address {
            get {
                return ResourceManager.GetString("EmailReport_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something unexpected went wrong. The journal was not sent..
        /// </summary>
        public static string EmailReport_Exception {
            get {
                return ResourceManager.GetString("EmailReport_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal by AAA
        ///Questions or comments? Reply to BBB.
        /// </summary>
        public static string EmailReport_Footer1 {
            get {
                return ResourceManager.GetString("EmailReport_Footer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal by AAA.
        /// </summary>
        public static string EmailReport_Footer1a {
            get {
                return ResourceManager.GetString("EmailReport_Footer1a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions or comments? Reply to BBB.
        /// </summary>
        public static string EmailReport_Footer1b {
            get {
                return ResourceManager.GetString("EmailReport_Footer1b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: Most, but not all data points in the database come from reputable sources. We do our best to make sure values are accurate, but cannot be held responsible for incorrect or missing data. By using the app, you acknowledge and accept full responsibility for checking the accuracy of the data. The app allows you to update any discrepancies you may find..
        /// </summary>
        public static string EmailReport_Footer2 {
            get {
                return ResourceManager.GetString("EmailReport_Footer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid e-mail address..
        /// </summary>
        public static string EmailReport_InvalidEmailAddress {
            get {
                return ResourceManager.GetString("EmailReport_InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send now.
        /// </summary>
        public static string EmailReport_SendNow {
            get {
                return ResourceManager.GetString("EmailReport_SendNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send by e-mail.
        /// </summary>
        public static string EmailReport_ShowSettings {
            get {
                return ResourceManager.GetString("EmailReport_ShowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Journal for {0}.
        /// </summary>
        public static string EmailReport_SubjectTemplate {
            get {
                return ResourceManager.GetString("EmailReport_SubjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing selected.
        /// </summary>
        public static string EmptyEntryList {
            get {
                return ResourceManager.GetString("EmptyEntryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a search term.
        /// </summary>
        public static string EmptySearchList {
            get {
                return ResourceManager.GetString("EmptySearchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count missing meals on the app tile.
        /// </summary>
        public static string EnableLiveTile {
            get {
                return ResourceManager.GetString("EnableLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At the end of the day.
        /// </summary>
        public static string EndOfDay {
            get {
                return ResourceManager.GetString("EndOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string EnterEquivalent {
            get {
                return ResourceManager.GetString("EnterEquivalent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the weight for this amount.
        /// </summary>
        public static string EnterTheWeightForThisAmount {
            get {
                return ResourceManager.GetString("EnterTheWeightForThisAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter weight first.
        /// </summary>
        public static string EnterWeight {
            get {
                return ResourceManager.GetString("EnterWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount:.
        /// </summary>
        public static string Equivalent {
            get {
                return ResourceManager.GetString("Equivalent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Now?.
        /// </summary>
        public static string ExpiredCaption {
            get {
                return ResourceManager.GetString("ExpiredCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using this App! This copy is now expired. But don&apos;t worry, we&apos;ll take you to the download page to update if you press Ok..
        /// </summary>
        public static string ExpiredMessage {
            get {
                return ResourceManager.GetString("ExpiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * NOTE: Most, but not all data comes from reputable sources. By purchasing the premium version, you accept full responsibility for the accuracy and completeness of the data. E-mail daily.journal@outlook.com for details..
        /// </summary>
        public static string Feature_Footer {
            get {
                return ResourceManager.GetString("Feature_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included:.
        /// </summary>
        public static string Feature_Header {
            get {
                return ResourceManager.GetString("Feature_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All advertisements are permanently removed.
        /// </summary>
        public static string Feature1_Desc {
            get {
                return ResourceManager.GetString("Feature1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No advertisements.
        /// </summary>
        public static string Feature1_Text {
            get {
                return ResourceManager.GetString("Feature1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail your Journal to save, print, or analyze it.
        /// </summary>
        public static string Feature2_Desc {
            get {
                return ResourceManager.GetString("Feature2_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail reports.
        /// </summary>
        public static string Feature2_Text {
            get {
                return ResourceManager.GetString("Feature2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hundreds to thousands more food items (depending on location).
        /// </summary>
        public static string Feature3_Desc {
            get {
                return ResourceManager.GetString("Feature3_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More foods *.
        /// </summary>
        public static string Feature3_Text {
            get {
                return ResourceManager.GetString("Feature3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For tracking 5, 6 or more meals per day.
        /// </summary>
        public static string Feature4_Desc {
            get {
                return ResourceManager.GetString("Feature4_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More meals.
        /// </summary>
        public static string Feature4_Text {
            get {
                return ResourceManager.GetString("Feature4_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All premium features in future updates.
        /// </summary>
        public static string Feature5_Desc {
            get {
                return ResourceManager.GetString("Feature5_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New features.
        /// </summary>
        public static string Feature5_Text {
            get {
                return ResourceManager.GetString("Feature5_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help to keep updates of this app coming.
        /// </summary>
        public static string Feature6_Desc {
            get {
                return ResourceManager.GetString("Feature6_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support the development.
        /// </summary>
        public static string Feature6_Text {
            get {
                return ResourceManager.GetString("Feature6_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a problem.
        /// </summary>
        public static string Feedback_Email {
            get {
                return ResourceManager.GetString("Feedback_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or suggest a feature or ask a question.
        /// </summary>
        public static string Feedback_EmailText {
            get {
                return ResourceManager.GetString("Feedback_EmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCLAIMER:
        ///Most, but not all data points in the database come from reputable sources. We do our best to make sure all values are accurate, but cannot be held responsible for incorrect or missing data. Nutritional values vary by brand and over time. By using this app, you agree to verify and correct any data in the app, and to be fully responsible for injury or damage due to its usage.
        ///
        ///Please let me know if there is anything I can help you with..
        /// </summary>
        public static string Feedback_Footer {
            get {
                return ResourceManager.GetString("Feedback_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quickest and easiest way to keep track of what you eat.
        ///
        ///Scroll down for information about data accuracy..
        /// </summary>
        public static string Feedback_Header {
            get {
                return ResourceManager.GetString("Feedback_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improve translations.
        /// </summary>
        public static string Feedback_Localize {
            get {
                return ResourceManager.GetString("Feedback_Localize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help improve the app.
        /// </summary>
        public static string Feedback_LocalizeText {
            get {
                return ResourceManager.GetString("Feedback_LocalizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this app.
        /// </summary>
        public static string Feedback_Rate {
            get {
                return ResourceManager.GetString("Feedback_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific feedback helps improve the app.
        /// </summary>
        public static string Feedback_RateText {
            get {
                return ResourceManager.GetString("Feedback_RateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Ads.
        /// </summary>
        public static string Feedback_RemoveAds {
            get {
                return ResourceManager.GetString("Feedback_RemoveAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanently remove all advertisements.
        /// </summary>
        public static string Feedback_RemoveAdsText {
            get {
                return ResourceManager.GetString("Feedback_RemoveAdsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help improve the translation.
        /// </summary>
        public static string Feedback_Screenshot {
            get {
                return ResourceManager.GetString("Feedback_Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A screen capture is included.
        /// </summary>
        public static string Feedback_ScreenshotText {
            get {
                return ResourceManager.GetString("Feedback_ScreenshotText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share a link.
        /// </summary>
        public static string Feedback_Share {
            get {
                return ResourceManager.GetString("Feedback_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To download this app.
        /// </summary>
        public static string Feedback_ShareText {
            get {
                return ResourceManager.GetString("Feedback_ShareText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade now.
        /// </summary>
        public static string Feedback_Unlock {
            get {
                return ResourceManager.GetString("Feedback_Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy the premium version.
        /// </summary>
        public static string Feedback_UnlockText {
            get {
                return ResourceManager.GetString("Feedback_UnlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail from Food Diary.
        /// </summary>
        public static string FeedbackSubject {
            get {
                return ResourceManager.GetString("FeedbackSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ALL features.
        /// </summary>
        public static string GetAllFeatures {
            get {
                return ResourceManager.GetString("GetAllFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} over goal.
        /// </summary>
        public static string GoalOver {
            get {
                return ResourceManager.GetString("GoalOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        public static string Goals {
            get {
                return ResourceManager.GetString("Goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} remaining.
        /// </summary>
        public static string GoalUnder {
            get {
                return ResourceManager.GetString("GoalUnder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much?.
        /// </summary>
        public static string HowMuch {
            get {
                return ResourceManager.GetString("HowMuch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        public static string Ingredients {
            get {
                return ResourceManager.GetString("Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Localization_Comment {
            get {
                return ResourceManager.GetString("Localization_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your e-mail address if you want to be contacted..
        /// </summary>
        public static string Localization_CommentText {
            get {
                return ResourceManager.GetString("Localization_CommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Localization_Description {
            get {
                return ResourceManager.GetString("Localization_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string Localization_Good {
            get {
                return ResourceManager.GetString("Localization_Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original:.
        /// </summary>
        public static string Localization_Original {
            get {
                return ResourceManager.GetString("Localization_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Localization_Submit {
            get {
                return ResourceManager.GetString("Localization_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can help to improve this app..
        /// </summary>
        public static string Localization_Text {
            get {
                return ResourceManager.GetString("Localization_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your help!.
        /// </summary>
        public static string Localization_ThankYou {
            get {
                return ResourceManager.GetString("Localization_ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        public static string Localization_Translations {
            get {
                return ResourceManager.GetString("Localization_Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please update the texts in this list with better translations. Remove all text for items that are inappropriate for your region..
        /// </summary>
        public static string Localization_TranslationsText {
            get {
                return ResourceManager.GetString("Localization_TranslationsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meals.
        /// </summary>
        public static string Meals {
            get {
                return ResourceManager.GetString("Meals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separate afternoon snack.
        /// </summary>
        public static string Meals_SnackAfternoonEnabled {
            get {
                return ResourceManager.GetString("Meals_SnackAfternoonEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separate early afternoon snack.
        /// </summary>
        public static string Meals_SnackEarlyAfternoonEnabled {
            get {
                return ResourceManager.GetString("Meals_SnackEarlyAfternoonEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separate evening snack.
        /// </summary>
        public static string Meals_SnackEveningEnabled {
            get {
                return ResourceManager.GetString("Meals_SnackEveningEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separate midnight snack.
        /// </summary>
        public static string Meals_SnackMidnightEnabled {
            get {
                return ResourceManager.GetString("Meals_SnackMidnightEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separate morning snack.
        /// </summary>
        public static string Meals_SnackMorningEnabled {
            get {
                return ResourceManager.GetString("Meals_SnackMorningEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine snacks.
        /// </summary>
        public static string Meals_SnacksCombined {
            get {
                return ResourceManager.GetString("Meals_SnacksCombined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more options.
        /// </summary>
        public static string MoreOptions {
            get {
                return ResourceManager.GetString("MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More options.
        /// </summary>
        public static string MoreOptions2 {
            get {
                return ResourceManager.GetString("MoreOptions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent breakfast items.
        /// </summary>
        public static string MyRecentItems_Breakfast {
            get {
                return ResourceManager.GetString("MyRecentItems_Breakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent dinner items.
        /// </summary>
        public static string MyRecentItems_Dinner {
            get {
                return ResourceManager.GetString("MyRecentItems_Dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My recent excersizes.
        /// </summary>
        public static string MyRecentItems_Exercise {
            get {
                return ResourceManager.GetString("MyRecentItems_Exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent lunch items.
        /// </summary>
        public static string MyRecentItems_Lunch {
            get {
                return ResourceManager.GetString("MyRecentItems_Lunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent snack items.
        /// </summary>
        public static string MyRecentItems_Snack {
            get {
                return ResourceManager.GetString("MyRecentItems_Snack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent afternoon items.
        /// </summary>
        public static string MyRecentItems_SnackAfternoon {
            get {
                return ResourceManager.GetString("MyRecentItems_SnackAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent early afternoon items.
        /// </summary>
        public static string MyRecentItems_SnackEarlyAfternoon {
            get {
                return ResourceManager.GetString("MyRecentItems_SnackEarlyAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent evening items.
        /// </summary>
        public static string MyRecentItems_SnackEvening {
            get {
                return ResourceManager.GetString("MyRecentItems_SnackEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent midnight items.
        /// </summary>
        public static string MyRecentItems_SnackMidnight {
            get {
                return ResourceManager.GetString("MyRecentItems_SnackMidnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent morning items.
        /// </summary>
        public static string MyRecentItems_SnackMorning {
            get {
                return ResourceManager.GetString("MyRecentItems_SnackMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (new item).
        /// </summary>
        public static string NewItemSuffix {
            get {
                return ResourceManager.GetString("NewItemSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (new recipe).
        /// </summary>
        public static string NewRecipeSuffix {
            get {
                return ResourceManager.GetString("NewRecipeSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No goal set.
        /// </summary>
        public static string NoGoalSet {
            get {
                return ResourceManager.GetString("NoGoalSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no ingredients.
        /// </summary>
        public static string NoIngredients {
            get {
                return ResourceManager.GetString("NoIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No nutrition information.
        /// </summary>
        public static string NoNutritionInfo {
            get {
                return ResourceManager.GetString("NoNutritionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutrition.
        /// </summary>
        public static string Nutrition {
            get {
                return ResourceManager.GetString("Nutrition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day sale: {0}% off.
        /// </summary>
        public static string OneDaySalePctOff {
            get {
                return ResourceManager.GetString("OneDaySalePctOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 serving.
        /// </summary>
        public static string OneServing {
            get {
                return ResourceManager.GetString("OneServing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        public static string OpenJournal {
            get {
                return ResourceManager.GetString("OpenJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string OpenReport {
            get {
                return ResourceManager.GetString("OpenReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOOD DIARY.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOOD DIARY - .
        /// </summary>
        public static string PageTitleBase {
            get {
                return ResourceManager.GetString("PageTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOOD INFO.
        /// </summary>
        public static string PageTitleItemDetail {
            get {
                return ResourceManager.GetString("PageTitleItemDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe.
        /// </summary>
        public static string PageTitleRecipe {
            get {
                return ResourceManager.GetString("PageTitleRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My preferences.
        /// </summary>
        public static string PageTitleSettings {
            get {
                return ResourceManager.GetString("PageTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakfast.
        /// </summary>
        public static string Period_Breakfast {
            get {
                return ResourceManager.GetString("Period_Breakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner.
        /// </summary>
        public static string Period_Dinner {
            get {
                return ResourceManager.GetString("Period_Dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise.
        /// </summary>
        public static string Period_Exercise {
            get {
                return ResourceManager.GetString("Period_Exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch.
        /// </summary>
        public static string Period_Lunch {
            get {
                return ResourceManager.GetString("Period_Lunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snack.
        /// </summary>
        public static string Period_Snack {
            get {
                return ResourceManager.GetString("Period_Snack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afternoon.
        /// </summary>
        public static string Period_SnackAfternoon {
            get {
                return ResourceManager.GetString("Period_SnackAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early afternoon.
        /// </summary>
        public static string Period_SnackEarlyAfternoon {
            get {
                return ResourceManager.GetString("Period_SnackEarlyAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evening.
        /// </summary>
        public static string Period_SnackEvening {
            get {
                return ResourceManager.GetString("Period_SnackEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midnight.
        /// </summary>
        public static string Period_SnackMidnight {
            get {
                return ResourceManager.GetString("Period_SnackMidnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning.
        /// </summary>
        public static string Period_SnackMorning {
            get {
                return ResourceManager.GetString("Period_SnackMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up the tile.
        /// </summary>
        public static string PinToStart {
            get {
                return ResourceManager.GetString("PinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only {0}.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Advertisements.
        /// </summary>
        public static string Product_1 {
            get {
                return ResourceManager.GetString("Product_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your support! Use this option to permanently remove advertisements from your Food Diary app..
        /// </summary>
        public static string Product_2 {
            get {
                return ResourceManager.GetString("Product_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade to premium.
        /// </summary>
        public static string Product_3 {
            get {
                return ResourceManager.GetString("Product_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get access to all features.
        /// </summary>
        public static string Product_4 {
            get {
                return ResourceManager.GetString("Product_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Recipes.
        /// </summary>
        public static string Recipes {
            get {
                return ResourceManager.GetString("Recipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What did you eat?.
        /// </summary>
        public static string ReminderContent {
            get {
                return ResourceManager.GetString("ReminderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected reminders appear if you haven&apos;t updated your diary by the selected time.
        /// </summary>
        public static string ReminderDescription {
            get {
                return ResourceManager.GetString("ReminderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminders.
        /// </summary>
        public static string Reminders {
            get {
                return ResourceManager.GetString("Reminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: update your diary.
        /// </summary>
        public static string ReminderTitle {
            get {
                return ResourceManager.GetString("ReminderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose OK to remove advertisements from the app..
        /// </summary>
        public static string RemoveAdsText {
            get {
                return ResourceManager.GetString("RemoveAdsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Advertisements?.
        /// </summary>
        public static string RemoveAdsTitle {
            get {
                return ResourceManager.GetString("RemoveAdsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using this App! If you find it useful, please help it become successful by leaving a review..
        /// </summary>
        public static string ReviewBody {
            get {
                return ResourceManager.GetString("ReviewBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a review?.
        /// </summary>
        public static string ReviewTitle {
            get {
                return ResourceManager.GetString("ReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange juice.
        /// </summary>
        public static string Screenshot_1a {
            get {
                return ResourceManager.GetString("Screenshot_1a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 cup.
        /// </summary>
        public static string Screenshot_1b {
            get {
                return ResourceManager.GetString("Screenshot_1b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toast.
        /// </summary>
        public static string Screenshot_2a {
            get {
                return ResourceManager.GetString("Screenshot_2a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 slice.
        /// </summary>
        public static string Screenshot_2b {
            get {
                return ResourceManager.GetString("Screenshot_2b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egg.
        /// </summary>
        public static string Screenshot_3a {
            get {
                return ResourceManager.GetString("Screenshot_3a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 medium.
        /// </summary>
        public static string Screenshot_3b {
            get {
                return ResourceManager.GetString("Screenshot_3b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple.
        /// </summary>
        public static string Screenshot_H1 {
            get {
                return ResourceManager.GetString("Screenshot_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee.
        /// </summary>
        public static string Screenshot_H2 {
            get {
                return ResourceManager.GetString("Screenshot_H2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banana.
        /// </summary>
        public static string Screenshot_H3 {
            get {
                return ResourceManager.GetString("Screenshot_H3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Diary text.
        /// </summary>
        public static string ScreenshotSubject {
            get {
                return ResourceManager.GetString("ScreenshotSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange juice, 1 cup, Toast, 1 slice, Egg, 1 medium, Apple, Coffee, Banana.
        /// </summary>
        public static string ScreenshotTitles {
            get {
                return ResourceManager.GetString("ScreenshotTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found, try changing your search term.
        /// </summary>
        public static string SearchTermNotFound {
            get {
                return ResourceManager.GetString("SearchTermNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string SendFeedback {
            get {
                return ResourceManager.GetString("SendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serving size.
        /// </summary>
        public static string ServingSizes {
            get {
                return ResourceManager.GetString("ServingSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsScreen {
            get {
                return ResourceManager.GetString("SettingsScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out Food Diary for Windows Phone.
        /// </summary>
        public static string ShareMessage {
            get {
                return ResourceManager.GetString("ShareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Diary.
        /// </summary>
        public static string ShareTitle {
            get {
                return ResourceManager.GetString("ShareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string StandardProperty_Amount {
            get {
                return ResourceManager.GetString("StandardProperty_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcium.
        /// </summary>
        public static string StandardProperty_Calcium {
            get {
                return ResourceManager.GetString("StandardProperty_Calcium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories.
        /// </summary>
        public static string StandardProperty_Calories {
            get {
                return ResourceManager.GetString("StandardProperty_Calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbs.
        /// </summary>
        public static string StandardProperty_Carbs {
            get {
                return ResourceManager.GetString("StandardProperty_Carbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cholesterol.
        /// </summary>
        public static string StandardProperty_Cholesterol {
            get {
                return ResourceManager.GetString("StandardProperty_Cholesterol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiber.
        /// </summary>
        public static string StandardProperty_Fiber {
            get {
                return ResourceManager.GetString("StandardProperty_Fiber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron.
        /// </summary>
        public static string StandardProperty_Iron {
            get {
                return ResourceManager.GetString("StandardProperty_Iron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monounsaturated fat.
        /// </summary>
        public static string StandardProperty_MonoFat {
            get {
                return ResourceManager.GetString("StandardProperty_MonoFat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyunsaturated fat.
        /// </summary>
        public static string StandardProperty_PolyFat {
            get {
                return ResourceManager.GetString("StandardProperty_PolyFat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potassium.
        /// </summary>
        public static string StandardProperty_Potassium {
            get {
                return ResourceManager.GetString("StandardProperty_Potassium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protein.
        /// </summary>
        public static string StandardProperty_Protein {
            get {
                return ResourceManager.GetString("StandardProperty_Protein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturated fat.
        /// </summary>
        public static string StandardProperty_SatFat {
            get {
                return ResourceManager.GetString("StandardProperty_SatFat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sodium.
        /// </summary>
        public static string StandardProperty_Sodium {
            get {
                return ResourceManager.GetString("StandardProperty_Sodium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugar.
        /// </summary>
        public static string StandardProperty_Sugar {
            get {
                return ResourceManager.GetString("StandardProperty_Sugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total fat.
        /// </summary>
        public static string StandardProperty_TotalFat {
            get {
                return ResourceManager.GetString("StandardProperty_TotalFat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin C.
        /// </summary>
        public static string StandardProperty_VitaminC {
            get {
                return ResourceManager.GetString("StandardProperty_VitaminC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin D.
        /// </summary>
        public static string StandardProperty_VitaminD {
            get {
                return ResourceManager.GetString("StandardProperty_VitaminD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string StandardProperty_Weight {
            get {
                return ResourceManager.GetString("StandardProperty_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The was a problem connecting to the Windows Phone store. Please try again later..
        /// </summary>
        public static string StoreException {
            get {
                return ResourceManager.GetString("StoreException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calorie counter.
        /// </summary>
        public static string StoreKeyword_1 {
            get {
                return ResourceManager.GetString("StoreKeyword_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food journal.
        /// </summary>
        public static string StoreKeyword_2 {
            get {
                return ResourceManager.GetString("StoreKeyword_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet.
        /// </summary>
        public static string StoreKeyword_3 {
            get {
                return ResourceManager.GetString("StoreKeyword_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories.
        /// </summary>
        public static string StoreKeyword_4 {
            get {
                return ResourceManager.GetString("StoreKeyword_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutrition.
        /// </summary>
        public static string StoreKeyword_5 {
            get {
                return ResourceManager.GetString("StoreKeyword_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Diary: Your diet and calorie tracking app..
        /// </summary>
        public static string StoreText_1 {
            get {
                return ResourceManager.GetString("StoreText_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT THE APP:
        ///Keeping track of what you eat has been shown to help prevent and stop over-eating.
        ///This app helps you control your diet and eat healthier, by making it easy to track what you eat. The design is optimized to make entry as quick as possible, with 1 click entry, and recent food suggestions. The built in database already has thousands of food items and if yours are not known, adding them is easy.
        ///
        ///PLEASE NOTE: 
        ///This app is free to download, and supported by advertisements. You can use it for [rest of string was truncated]&quot;;.
        /// </summary>
        public static string StoreText_2 {
            get {
                return ResourceManager.GetString("StoreText_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEATURES:
        ///1. A simple and powerful design: The app opens directly on the entry screen, on the most recent meal, because that is what you&apos;ll use most. The design makes adding entries as simple and intuitive as possible.
        ///2. One tap entry with personalized suggestions: The most common food items can immediately be selected. Starting on the second day, your recent items are suggested because you may eat the same food frequently.
        ///3. Logging in is not needed: No personal data or contact information is required [rest of string was truncated]&quot;;.
        /// </summary>
        public static string StoreText_3 {
            get {
                return ResourceManager.GetString("StoreText_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREMIUM FEATURES:
        ///1. No more advertisement.
        ///2. A much larger food database.
        ///3. The ability to e-mail yourself a copy of the dairy.
        ///4. More configuration options, including the ability to enter up to 8 separate meals a day..
        /// </summary>
        public static string StoreText_4 {
            get {
                return ResourceManager.GetString("StoreText_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download now because you will love using it..
        /// </summary>
        public static string StoreText_5 {
            get {
                return ResourceManager.GetString("StoreText_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a picture.
        /// </summary>
        public static string TakeAPicture {
            get {
                return ResourceManager.GetString("TakeAPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total2 {
            get {
                return ResourceManager.GetString("Total2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your trial is now expired. You can still view your journal, but you can&apos;t add new entries. Choose OK to unlock the full version..
        /// </summary>
        public static string TrialExpiredBody {
            get {
                return ResourceManager.GetString("TrialExpiredBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial period expired, unlock?.
        /// </summary>
        public static string TrialExpiredTitle {
            get {
                return ResourceManager.GetString("TrialExpiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centiliter.
        /// </summary>
        public static string Unit_Centiliter {
            get {
                return ResourceManager.GetString("Unit_Centiliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cup.
        /// </summary>
        public static string Unit_Cup {
            get {
                return ResourceManager.GetString("Unit_Cup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deciliter.
        /// </summary>
        public static string Unit_Deciliter {
            get {
                return ResourceManager.GetString("Unit_Deciliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluid ounce.
        /// </summary>
        public static string Unit_FluidOunce {
            get {
                return ResourceManager.GetString("Unit_FluidOunce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallon.
        /// </summary>
        public static string Unit_Gallon {
            get {
                return ResourceManager.GetString("Unit_Gallon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gram.
        /// </summary>
        public static string Unit_Gram {
            get {
                return ResourceManager.GetString("Unit_Gram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilogram.
        /// </summary>
        public static string Unit_Kilogram {
            get {
                return ResourceManager.GetString("Unit_Kilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liter.
        /// </summary>
        public static string Unit_Liter {
            get {
                return ResourceManager.GetString("Unit_Liter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliliter.
        /// </summary>
        public static string Unit_Milliliter {
            get {
                return ResourceManager.GetString("Unit_Milliliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ounce.
        /// </summary>
        public static string Unit_Ounce {
            get {
                return ResourceManager.GetString("Unit_Ounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pint.
        /// </summary>
        public static string Unit_Pint {
            get {
                return ResourceManager.GetString("Unit_Pint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pound.
        /// </summary>
        public static string Unit_Pound {
            get {
                return ResourceManager.GetString("Unit_Pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quart.
        /// </summary>
        public static string Unit_Quart {
            get {
                return ResourceManager.GetString("Unit_Quart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablespoon.
        /// </summary>
        public static string Unit_Tablespoon {
            get {
                return ResourceManager.GetString("Unit_Tablespoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaspoon.
        /// </summary>
        public static string Unit_Teaspoon {
            get {
                return ResourceManager.GetString("Unit_Teaspoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centiliters.
        /// </summary>
        public static string Units_Centiliter {
            get {
                return ResourceManager.GetString("Units_Centiliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cups.
        /// </summary>
        public static string Units_Cup {
            get {
                return ResourceManager.GetString("Units_Cup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deciliters.
        /// </summary>
        public static string Units_Deciliter {
            get {
                return ResourceManager.GetString("Units_Deciliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluid ounces.
        /// </summary>
        public static string Units_FluidOunce {
            get {
                return ResourceManager.GetString("Units_FluidOunce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallons.
        /// </summary>
        public static string Units_Gallon {
            get {
                return ResourceManager.GetString("Units_Gallon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grams.
        /// </summary>
        public static string Units_Gram {
            get {
                return ResourceManager.GetString("Units_Gram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilograms.
        /// </summary>
        public static string Units_Kilogram {
            get {
                return ResourceManager.GetString("Units_Kilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liters.
        /// </summary>
        public static string Units_Liter {
            get {
                return ResourceManager.GetString("Units_Liter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliliters.
        /// </summary>
        public static string Units_Milliliter {
            get {
                return ResourceManager.GetString("Units_Milliliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ounces.
        /// </summary>
        public static string Units_Ounce {
            get {
                return ResourceManager.GetString("Units_Ounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pints.
        /// </summary>
        public static string Units_Pint {
            get {
                return ResourceManager.GetString("Units_Pint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pounds.
        /// </summary>
        public static string Units_Pound {
            get {
                return ResourceManager.GetString("Units_Pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarts.
        /// </summary>
        public static string Units_Quart {
            get {
                return ResourceManager.GetString("Units_Quart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablespoons.
        /// </summary>
        public static string Units_Tablespoon {
            get {
                return ResourceManager.GetString("Units_Tablespoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaspoons.
        /// </summary>
        public static string Units_Teaspoon {
            get {
                return ResourceManager.GetString("Units_Teaspoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for trying the Food Diary. You have {0} trial days remaining. Press OK to unlock the app..
        /// </summary>
        public static string UnlockFullBody {
            get {
                return ResourceManager.GetString("UnlockFullBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock now?.
        /// </summary>
        public static string UnlockFullTitle {
            get {
                return ResourceManager.GetString("UnlockFullTitle", resourceCulture);
            }
        }
    }
}
