// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using FoodJournal.Values;
using FoodJournal.ViewModels;
using FoodJournal.Runtime;

namespace FoodDiary2.iOS.Controller
{
	public partial class FDSelectItemVC : UIViewController
	{



		public FDSelectItemVC (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			SearchVM vm = new SearchVM( Navigate.selectedPeriod);
			tableview.Source = new FDSelectItemVCSource (vm);
			tableview.ReloadData ();

		}

		partial void cancelBtnTapped (UIKit.UIBarButtonItem sender)
		{
//			NavigationController.ParentViewController.NavigationController.PopViewController(true);	
		}

		partial void segmentedControlValueChanged (UISegmentedControl sender){

		}


		partial void selectItemBtnTapped (UIBarButtonItem sender){

		}

	}
}
