// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace FoodDiary2.iOS.Controller
{
	public partial class FDReportVC : UIViewController
	{
		public FDReportVC (IntPtr handle) : base (handle)
		{
		}

		partial void menuBtnTapped (UIBarButtonItem sender)
		{
			AppDelegate.SidebarController.ToggleMenu ();	
		}
	}
}
