//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodJournal.Common.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoodJournal.Common.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AcceptNew {
            get {
                return ResourceManager.GetString("AcceptNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a serving size.
        /// </summary>
        internal static string AddServingSize {
            get {
                return ResourceManager.GetString("AddServingSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to launcher.
        /// </summary>
        internal static string AddToLauncher {
            get {
                return ResourceManager.GetString("AddToLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisement.
        /// </summary>
        internal static string Advertisement {
            get {
                return ResourceManager.GetString("Advertisement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This task updates the Live Tile for the Food Diary..
        /// </summary>
        internal static string AgentDescription {
            get {
                return ResourceManager.GetString("AgentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have disabled the Live Tile application in phone settings..
        /// </summary>
        internal static string AgentDisabled {
            get {
                return ResourceManager.GetString("AgentDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOOD DIARY.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Diary.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg.
        /// </summary>
        internal static string Avg {
            get {
                return ResourceManager.GetString("Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buy now.
        /// </summary>
        internal static string BuyNow {
            get {
                return ResourceManager.GetString("BuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter weight.
        /// </summary>
        internal static string CantCalculateNutrition {
            get {
                return ResourceManager.GetString("CantCalculateNutrition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string CommaListSeparater {
            get {
                return ResourceManager.GetString("CommaListSeparater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common items.
        /// </summary>
        internal static string CommonItems {
            get {
                return ResourceManager.GetString("CommonItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common breakfast items.
        /// </summary>
        internal static string CommonItems_Breakfast {
            get {
                return ResourceManager.GetString("CommonItems_Breakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common dinner items.
        /// </summary>
        internal static string CommonItems_Dinner {
            get {
                return ResourceManager.GetString("CommonItems_Dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common lunch items.
        /// </summary>
        internal static string CommonItems_Lunch {
            get {
                return ResourceManager.GetString("CommonItems_Lunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common snack items.
        /// </summary>
        internal static string CommonItems_Snack {
            get {
                return ResourceManager.GetString("CommonItems_Snack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common afternoon items.
        /// </summary>
        internal static string CommonItems_SnackAfternoon {
            get {
                return ResourceManager.GetString("CommonItems_SnackAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common early afternoon items.
        /// </summary>
        internal static string CommonItems_SnackEarlyAfternoon {
            get {
                return ResourceManager.GetString("CommonItems_SnackEarlyAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common evening items.
        /// </summary>
        internal static string CommonItems_SnackEvening {
            get {
                return ResourceManager.GetString("CommonItems_SnackEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common midnight items.
        /// </summary>
        internal static string CommonItems_SnackMidnight {
            get {
                return ResourceManager.GetString("CommonItems_SnackMidnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common morning items.
        /// </summary>
        internal static string CommonItems_SnackMorning {
            get {
                return ResourceManager.GetString("CommonItems_SnackMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100 g|1 oz=28 g|Teaspoon=4.5 g|Tablespoon=12 g|1 serving=28 g|Piece=14 g|Slice=12 g|1 cup=237 g.
        /// </summary>
        internal static string CommonServingSizes {
            get {
                return ResourceManager.GetString("CommonServingSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooking time.
        /// </summary>
        internal static string CookingTime {
            get {
                return ResourceManager.GetString("CookingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy from similar item.
        /// </summary>
        internal static string CopyFromSimilarItem {
            get {
                return ResourceManager.GetString("CopyFromSimilarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string DatabaseCulture {
            get {
                return ResourceManager.GetString("DatabaseCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete entry.
        /// </summary>
        internal static string DeleteEntry {
            get {
                return ResourceManager.GetString("DeleteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address.
        /// </summary>
        internal static string EmailReport_Address {
            get {
                return ResourceManager.GetString("EmailReport_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something unexpected went wrong. The journal was not sent..
        /// </summary>
        internal static string EmailReport_Exception {
            get {
                return ResourceManager.GetString("EmailReport_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal by AAA
        ///Questions or comments? Reply to BBB.
        /// </summary>
        internal static string EmailReport_Footer1 {
            get {
                return ResourceManager.GetString("EmailReport_Footer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal by AAA.
        /// </summary>
        internal static string EmailReport_Footer1a {
            get {
                return ResourceManager.GetString("EmailReport_Footer1a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions or comments? Reply to BBB.
        /// </summary>
        internal static string EmailReport_Footer1b {
            get {
                return ResourceManager.GetString("EmailReport_Footer1b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: Most, but not all data points in the database come from reputable sources. We do our best to make sure values are accurate, but cannot be held responsible for incorrect or missing data. By using the app, you acknowledge and accept full responsibility for checking the accuracy of the data. The app allows you to update any discrepancies you may find..
        /// </summary>
        internal static string EmailReport_Footer2 {
            get {
                return ResourceManager.GetString("EmailReport_Footer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid e-mail address..
        /// </summary>
        internal static string EmailReport_InvalidEmailAddress {
            get {
                return ResourceManager.GetString("EmailReport_InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send now.
        /// </summary>
        internal static string EmailReport_SendNow {
            get {
                return ResourceManager.GetString("EmailReport_SendNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send by e-mail.
        /// </summary>
        internal static string EmailReport_ShowSettings {
            get {
                return ResourceManager.GetString("EmailReport_ShowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Journal for {0}.
        /// </summary>
        internal static string EmailReport_SubjectTemplate {
            get {
                return ResourceManager.GetString("EmailReport_SubjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing selected.
        /// </summary>
        internal static string EmptyEntryList {
            get {
                return ResourceManager.GetString("EmptyEntryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a search term.
        /// </summary>
        internal static string EmptySearchList {
            get {
                return ResourceManager.GetString("EmptySearchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count missing meals on the app tile.
        /// </summary>
        internal static string EnableLiveTile {
            get {
                return ResourceManager.GetString("EnableLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At the end of the day.
        /// </summary>
        internal static string EndOfDay {
            get {
                return ResourceManager.GetString("EndOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string EnterEquivalent {
            get {
                return ResourceManager.GetString("EnterEquivalent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the weight for this amount.
        /// </summary>
        internal static string EnterTheWeightForThisAmount {
            get {
                return ResourceManager.GetString("EnterTheWeightForThisAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter weight first.
        /// </summary>
        internal static string EnterWeight {
            get {
                return ResourceManager.GetString("EnterWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount:.
        /// </summary>
        internal static string Equivalent {
            get {
                return ResourceManager.GetString("Equivalent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Now?.
        /// </summary>
        internal static string ExpiredCaption {
            get {
                return ResourceManager.GetString("ExpiredCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using this App! This copy is now expired. But don&apos;t worry, we&apos;ll take you to the download page to update if you press Ok..
        /// </summary>
        internal static string ExpiredMessage {
            get {
                return ResourceManager.GetString("ExpiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * NOTE: Most, but not all data comes from reputable sources. By purchasing the premium version, you accept full responsibility for the accuracy and completeness of the data. E-mail daily.journal@outlook.com for details..
        /// </summary>
        internal static string Feature_Footer {
            get {
                return ResourceManager.GetString("Feature_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included:.
        /// </summary>
        internal static string Feature_Header {
            get {
                return ResourceManager.GetString("Feature_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All advertisements are permanently removed.
        /// </summary>
        internal static string Feature1_Desc {
            get {
                return ResourceManager.GetString("Feature1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No advertisements.
        /// </summary>
        internal static string Feature1_Text {
            get {
                return ResourceManager.GetString("Feature1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail your Journal to save, print, or analyze it.
        /// </summary>
        internal static string Feature2_Desc {
            get {
                return ResourceManager.GetString("Feature2_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail reports.
        /// </summary>
        internal static string Feature2_Text {
            get {
                return ResourceManager.GetString("Feature2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hundreds to thousands more food items (depending on location).
        /// </summary>
        internal static string Feature3_Desc {
            get {
                return ResourceManager.GetString("Feature3_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More foods *.
        /// </summary>
        internal static string Feature3_Text {
            get {
                return ResourceManager.GetString("Feature3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For tracking 5, 6 or more meals per day.
        /// </summary>
        internal static string Feature4_Desc {
            get {
                return ResourceManager.GetString("Feature4_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More meals.
        /// </summary>
        internal static string Feature4_Text {
            get {
                return ResourceManager.GetString("Feature4_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All premium features in future updates.
        /// </summary>
        internal static string Feature5_Desc {
            get {
                return ResourceManager.GetString("Feature5_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New features.
        /// </summary>
        internal static string Feature5_Text {
            get {
                return ResourceManager.GetString("Feature5_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help to keep updates of this app coming.
        /// </summary>
        internal static string Feature6_Desc {
            get {
                return ResourceManager.GetString("Feature6_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support the development.
        /// </summary>
        internal static string Feature6_Text {
            get {
                return ResourceManager.GetString("Feature6_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a problem.
        /// </summary>
        internal static string Feedback_Email {
            get {
                return ResourceManager.GetString("Feedback_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or suggest a feature or ask a question.
        /// </summary>
        internal static string Feedback_EmailText {
            get {
                return ResourceManager.GetString("Feedback_EmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCLAIMER:
        ///Most, but not all data points in the database come from reputable sources. We do our best to make sure all values are accurate, but cannot be held responsible for incorrect or missing data. Nutritional values vary by brand and over time. By using this app, you agree to verify and correct any data in the app, and to be fully responsible for injury or damage due to its usage.
        ///
        ///Please let me know if there is anything I can help you with..
        /// </summary>
        internal static string Feedback_Footer {
            get {
                return ResourceManager.GetString("Feedback_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quickest and easiest way to keep track of what you eat.
        ///
        ///Scroll down for information about data accuracy..
        /// </summary>
        internal static string Feedback_Header {
            get {
                return ResourceManager.GetString("Feedback_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improve translations.
        /// </summary>
        internal static string Feedback_Localize {
            get {
                return ResourceManager.GetString("Feedback_Localize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help improve the app.
        /// </summary>
        internal static string Feedback_LocalizeText {
            get {
                return ResourceManager.GetString("Feedback_LocalizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this app.
        /// </summary>
        internal static string Feedback_Rate {
            get {
                return ResourceManager.GetString("Feedback_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific feedback helps improve the app.
        /// </summary>
        internal static string Feedback_RateText {
            get {
                return ResourceManager.GetString("Feedback_RateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Ads.
        /// </summary>
        internal static string Feedback_RemoveAds {
            get {
                return ResourceManager.GetString("Feedback_RemoveAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanently remove all advertisements.
        /// </summary>
        internal static string Feedback_RemoveAdsText {
            get {
                return ResourceManager.GetString("Feedback_RemoveAdsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help improve the translation.
        /// </summary>
        internal static string Feedback_Screenshot {
            get {
                return ResourceManager.GetString("Feedback_Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A screen capture is included.
        /// </summary>
        internal static string Feedback_ScreenshotText {
            get {
                return ResourceManager.GetString("Feedback_ScreenshotText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share a link.
        /// </summary>
        internal static string Feedback_Share {
            get {
                return ResourceManager.GetString("Feedback_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To download this app.
        /// </summary>
        internal static string Feedback_ShareText {
            get {
                return ResourceManager.GetString("Feedback_ShareText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade now.
        /// </summary>
        internal static string Feedback_Unlock {
            get {
                return ResourceManager.GetString("Feedback_Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy the premium version.
        /// </summary>
        internal static string Feedback_UnlockText {
            get {
                return ResourceManager.GetString("Feedback_UnlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail from Food Diary.
        /// </summary>
        internal static string FeedbackSubject {
            get {
                return ResourceManager.GetString("FeedbackSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ALL features.
        /// </summary>
        internal static string GetAllFeatures {
            get {
                return ResourceManager.GetString("GetAllFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} over goal.
        /// </summary>
        internal static string GoalOver {
            get {
                return ResourceManager.GetString("GoalOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        internal static string Goals {
            get {
                return ResourceManager.GetString("Goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} remaining.
        /// </summary>
        internal static string GoalUnder {
            get {
                return ResourceManager.GetString("GoalUnder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much?.
        /// </summary>
        internal static string HowMuch {
            get {
                return ResourceManager.GetString("HowMuch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        internal static string Ingredients {
            get {
                return ResourceManager.GetString("Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Localization_Comment {
            get {
                return ResourceManager.GetString("Localization_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your e-mail address if you want to be contacted..
        /// </summary>
        internal static string Localization_CommentText {
            get {
                return ResourceManager.GetString("Localization_CommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string Localization_Description {
            get {
                return ResourceManager.GetString("Localization_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        internal static string Localization_Good {
            get {
                return ResourceManager.GetString("Localization_Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original:.
        /// </summary>
        internal static string Localization_Original {
            get {
                return ResourceManager.GetString("Localization_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Localization_Submit {
            get {
                return ResourceManager.GetString("Localization_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can help to improve this app..
        /// </summary>
        internal static string Localization_Text {
            get {
                return ResourceManager.GetString("Localization_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your help!.
        /// </summary>
        internal static string Localization_ThankYou {
            get {
                return ResourceManager.GetString("Localization_ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        internal static string Localization_Translations {
            get {
                return ResourceManager.GetString("Localization_Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please update the texts in this list with better translations. Remove all text for items that are inappropriate for your region..
        /// </summary>
        internal static string Localization_TranslationsText {
            get {
                return ResourceManager.GetString("Localization_TranslationsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meals.
        /// </summary>
        internal static string Meals {
            get {
                return ResourceManager.GetString("Meals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separate afternoon snack.
        /// </summary>
        internal static string Meals_SnackAfternoonEnabled {
            get {
                return ResourceManager.GetString("Meals_SnackAfternoonEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separate early afternoon snack.
        /// </summary>
        internal static string Meals_SnackEarlyAfternoonEnabled {
            get {
                return ResourceManager.GetString("Meals_SnackEarlyAfternoonEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separate evening snack.
        /// </summary>
        internal static string Meals_SnackEveningEnabled {
            get {
                return ResourceManager.GetString("Meals_SnackEveningEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separate midnight snack.
        /// </summary>
        internal static string Meals_SnackMidnightEnabled {
            get {
                return ResourceManager.GetString("Meals_SnackMidnightEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separate morning snack.
        /// </summary>
        internal static string Meals_SnackMorningEnabled {
            get {
                return ResourceManager.GetString("Meals_SnackMorningEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine snacks.
        /// </summary>
        internal static string Meals_SnacksCombined {
            get {
                return ResourceManager.GetString("Meals_SnacksCombined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more options.
        /// </summary>
        internal static string MoreOptions {
            get {
                return ResourceManager.GetString("MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More options.
        /// </summary>
        internal static string MoreOptions2 {
            get {
                return ResourceManager.GetString("MoreOptions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent breakfast items.
        /// </summary>
        internal static string MyRecentItems_Breakfast {
            get {
                return ResourceManager.GetString("MyRecentItems_Breakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent dinner items.
        /// </summary>
        internal static string MyRecentItems_Dinner {
            get {
                return ResourceManager.GetString("MyRecentItems_Dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My recent excersizes.
        /// </summary>
        internal static string MyRecentItems_Exercise {
            get {
                return ResourceManager.GetString("MyRecentItems_Exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent lunch items.
        /// </summary>
        internal static string MyRecentItems_Lunch {
            get {
                return ResourceManager.GetString("MyRecentItems_Lunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent snack items.
        /// </summary>
        internal static string MyRecentItems_Snack {
            get {
                return ResourceManager.GetString("MyRecentItems_Snack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent afternoon items.
        /// </summary>
        internal static string MyRecentItems_SnackAfternoon {
            get {
                return ResourceManager.GetString("MyRecentItems_SnackAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent early afternoon items.
        /// </summary>
        internal static string MyRecentItems_SnackEarlyAfternoon {
            get {
                return ResourceManager.GetString("MyRecentItems_SnackEarlyAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent evening items.
        /// </summary>
        internal static string MyRecentItems_SnackEvening {
            get {
                return ResourceManager.GetString("MyRecentItems_SnackEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent midnight items.
        /// </summary>
        internal static string MyRecentItems_SnackMidnight {
            get {
                return ResourceManager.GetString("MyRecentItems_SnackMidnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent morning items.
        /// </summary>
        internal static string MyRecentItems_SnackMorning {
            get {
                return ResourceManager.GetString("MyRecentItems_SnackMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (new item).
        /// </summary>
        internal static string NewItemSuffix {
            get {
                return ResourceManager.GetString("NewItemSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (new recipe).
        /// </summary>
        internal static string NewRecipeSuffix {
            get {
                return ResourceManager.GetString("NewRecipeSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No goal set.
        /// </summary>
        internal static string NoGoalSet {
            get {
                return ResourceManager.GetString("NoGoalSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no ingredients.
        /// </summary>
        internal static string NoIngredients {
            get {
                return ResourceManager.GetString("NoIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No nutrition information.
        /// </summary>
        internal static string NoNutritionInfo {
            get {
                return ResourceManager.GetString("NoNutritionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutrition.
        /// </summary>
        internal static string Nutrition {
            get {
                return ResourceManager.GetString("Nutrition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day sale: {0}% off.
        /// </summary>
        internal static string OneDaySalePctOff {
            get {
                return ResourceManager.GetString("OneDaySalePctOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 serving.
        /// </summary>
        internal static string OneServing {
            get {
                return ResourceManager.GetString("OneServing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        internal static string OpenJournal {
            get {
                return ResourceManager.GetString("OpenJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string OpenReport {
            get {
                return ResourceManager.GetString("OpenReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOOD DIARY.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOOD DIARY - .
        /// </summary>
        internal static string PageTitleBase {
            get {
                return ResourceManager.GetString("PageTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOOD INFO.
        /// </summary>
        internal static string PageTitleItemDetail {
            get {
                return ResourceManager.GetString("PageTitleItemDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe.
        /// </summary>
        internal static string PageTitleRecipe {
            get {
                return ResourceManager.GetString("PageTitleRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My preferences.
        /// </summary>
        internal static string PageTitleSettings {
            get {
                return ResourceManager.GetString("PageTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakfast.
        /// </summary>
        internal static string Period_Breakfast {
            get {
                return ResourceManager.GetString("Period_Breakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner.
        /// </summary>
        internal static string Period_Dinner {
            get {
                return ResourceManager.GetString("Period_Dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise.
        /// </summary>
        internal static string Period_Exercise {
            get {
                return ResourceManager.GetString("Period_Exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch.
        /// </summary>
        internal static string Period_Lunch {
            get {
                return ResourceManager.GetString("Period_Lunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snack.
        /// </summary>
        internal static string Period_Snack {
            get {
                return ResourceManager.GetString("Period_Snack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afternoon.
        /// </summary>
        internal static string Period_SnackAfternoon {
            get {
                return ResourceManager.GetString("Period_SnackAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early afternoon.
        /// </summary>
        internal static string Period_SnackEarlyAfternoon {
            get {
                return ResourceManager.GetString("Period_SnackEarlyAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evening.
        /// </summary>
        internal static string Period_SnackEvening {
            get {
                return ResourceManager.GetString("Period_SnackEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midnight.
        /// </summary>
        internal static string Period_SnackMidnight {
            get {
                return ResourceManager.GetString("Period_SnackMidnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning.
        /// </summary>
        internal static string Period_SnackMorning {
            get {
                return ResourceManager.GetString("Period_SnackMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up the tile.
        /// </summary>
        internal static string PinToStart {
            get {
                return ResourceManager.GetString("PinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only {0}.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Advertisements.
        /// </summary>
        internal static string Product_1 {
            get {
                return ResourceManager.GetString("Product_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your support! Use this option to permanently remove advertisements from your Food Diary app..
        /// </summary>
        internal static string Product_2 {
            get {
                return ResourceManager.GetString("Product_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade to premium.
        /// </summary>
        internal static string Product_3 {
            get {
                return ResourceManager.GetString("Product_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get access to all features.
        /// </summary>
        internal static string Product_4 {
            get {
                return ResourceManager.GetString("Product_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Recipes.
        /// </summary>
        internal static string Recipes {
            get {
                return ResourceManager.GetString("Recipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What did you eat?.
        /// </summary>
        internal static string ReminderContent {
            get {
                return ResourceManager.GetString("ReminderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected reminders appear if you haven&apos;t updated your diary by the selected time.
        /// </summary>
        internal static string ReminderDescription {
            get {
                return ResourceManager.GetString("ReminderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminders.
        /// </summary>
        internal static string Reminders {
            get {
                return ResourceManager.GetString("Reminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: update your diary.
        /// </summary>
        internal static string ReminderTitle {
            get {
                return ResourceManager.GetString("ReminderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose OK to remove advertisements from the app..
        /// </summary>
        internal static string RemoveAdsText {
            get {
                return ResourceManager.GetString("RemoveAdsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Advertisements?.
        /// </summary>
        internal static string RemoveAdsTitle {
            get {
                return ResourceManager.GetString("RemoveAdsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        internal static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        internal static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using this App! If you find it useful, please help it become successful by leaving a review..
        /// </summary>
        internal static string ReviewBody {
            get {
                return ResourceManager.GetString("ReviewBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a review?.
        /// </summary>
        internal static string ReviewTitle {
            get {
                return ResourceManager.GetString("ReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange juice.
        /// </summary>
        internal static string Screenshot_1a {
            get {
                return ResourceManager.GetString("Screenshot_1a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 cup.
        /// </summary>
        internal static string Screenshot_1b {
            get {
                return ResourceManager.GetString("Screenshot_1b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toast.
        /// </summary>
        internal static string Screenshot_2a {
            get {
                return ResourceManager.GetString("Screenshot_2a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 slice.
        /// </summary>
        internal static string Screenshot_2b {
            get {
                return ResourceManager.GetString("Screenshot_2b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egg.
        /// </summary>
        internal static string Screenshot_3a {
            get {
                return ResourceManager.GetString("Screenshot_3a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 medium.
        /// </summary>
        internal static string Screenshot_3b {
            get {
                return ResourceManager.GetString("Screenshot_3b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple.
        /// </summary>
        internal static string Screenshot_H1 {
            get {
                return ResourceManager.GetString("Screenshot_H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee.
        /// </summary>
        internal static string Screenshot_H2 {
            get {
                return ResourceManager.GetString("Screenshot_H2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banana.
        /// </summary>
        internal static string Screenshot_H3 {
            get {
                return ResourceManager.GetString("Screenshot_H3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Diary text.
        /// </summary>
        internal static string ScreenshotSubject {
            get {
                return ResourceManager.GetString("ScreenshotSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange juice, 1 cup, Toast, 1 slice, Egg, 1 medium, Apple, Coffee, Banana.
        /// </summary>
        internal static string ScreenshotTitles {
            get {
                return ResourceManager.GetString("ScreenshotTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results.
        /// </summary>
        internal static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found, try changing your search term.
        /// </summary>
        internal static string SearchTermNotFound {
            get {
                return ResourceManager.GetString("SearchTermNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string SendFeedback {
            get {
                return ResourceManager.GetString("SendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serving size.
        /// </summary>
        internal static string ServingSizes {
            get {
                return ResourceManager.GetString("ServingSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsScreen {
            get {
                return ResourceManager.GetString("SettingsScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out Food Diary for Windows Phone.
        /// </summary>
        internal static string ShareMessage {
            get {
                return ResourceManager.GetString("ShareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Diary.
        /// </summary>
        internal static string ShareTitle {
            get {
                return ResourceManager.GetString("ShareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string StandardProperty_Amount {
            get {
                return ResourceManager.GetString("StandardProperty_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcium.
        /// </summary>
        internal static string StandardProperty_Calcium {
            get {
                return ResourceManager.GetString("StandardProperty_Calcium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories.
        /// </summary>
        internal static string StandardProperty_Calories {
            get {
                return ResourceManager.GetString("StandardProperty_Calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbs.
        /// </summary>
        internal static string StandardProperty_Carbs {
            get {
                return ResourceManager.GetString("StandardProperty_Carbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cholesterol.
        /// </summary>
        internal static string StandardProperty_Cholesterol {
            get {
                return ResourceManager.GetString("StandardProperty_Cholesterol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiber.
        /// </summary>
        internal static string StandardProperty_Fiber {
            get {
                return ResourceManager.GetString("StandardProperty_Fiber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron.
        /// </summary>
        internal static string StandardProperty_Iron {
            get {
                return ResourceManager.GetString("StandardProperty_Iron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monounsaturated fat.
        /// </summary>
        internal static string StandardProperty_MonoFat {
            get {
                return ResourceManager.GetString("StandardProperty_MonoFat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyunsaturated fat.
        /// </summary>
        internal static string StandardProperty_PolyFat {
            get {
                return ResourceManager.GetString("StandardProperty_PolyFat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potassium.
        /// </summary>
        internal static string StandardProperty_Potassium {
            get {
                return ResourceManager.GetString("StandardProperty_Potassium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protein.
        /// </summary>
        internal static string StandardProperty_Protein {
            get {
                return ResourceManager.GetString("StandardProperty_Protein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturated fat.
        /// </summary>
        internal static string StandardProperty_SatFat {
            get {
                return ResourceManager.GetString("StandardProperty_SatFat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sodium.
        /// </summary>
        internal static string StandardProperty_Sodium {
            get {
                return ResourceManager.GetString("StandardProperty_Sodium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugar.
        /// </summary>
        internal static string StandardProperty_Sugar {
            get {
                return ResourceManager.GetString("StandardProperty_Sugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total fat.
        /// </summary>
        internal static string StandardProperty_TotalFat {
            get {
                return ResourceManager.GetString("StandardProperty_TotalFat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin C.
        /// </summary>
        internal static string StandardProperty_VitaminC {
            get {
                return ResourceManager.GetString("StandardProperty_VitaminC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin D.
        /// </summary>
        internal static string StandardProperty_VitaminD {
            get {
                return ResourceManager.GetString("StandardProperty_VitaminD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string StandardProperty_Weight {
            get {
                return ResourceManager.GetString("StandardProperty_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The was a problem connecting to the Windows Phone store. Please try again later..
        /// </summary>
        internal static string StoreException {
            get {
                return ResourceManager.GetString("StoreException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calorie counter.
        /// </summary>
        internal static string StoreKeyword_1 {
            get {
                return ResourceManager.GetString("StoreKeyword_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food journal.
        /// </summary>
        internal static string StoreKeyword_2 {
            get {
                return ResourceManager.GetString("StoreKeyword_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet.
        /// </summary>
        internal static string StoreKeyword_3 {
            get {
                return ResourceManager.GetString("StoreKeyword_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories.
        /// </summary>
        internal static string StoreKeyword_4 {
            get {
                return ResourceManager.GetString("StoreKeyword_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutrition.
        /// </summary>
        internal static string StoreKeyword_5 {
            get {
                return ResourceManager.GetString("StoreKeyword_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Diary: Your diet and calorie tracking app..
        /// </summary>
        internal static string StoreText_1 {
            get {
                return ResourceManager.GetString("StoreText_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT THE APP:
        ///Keeping track of what you eat has been shown to help prevent and stop over-eating.
        ///This app helps you control your diet and eat healthier, by making it easy to track what you eat. The design is optimized to make entry as quick as possible, with 1 click entry, and recent food suggestions. The built in database already has thousands of food items and if yours are not known, adding them is easy.
        ///
        ///PLEASE NOTE: 
        ///This app is free to download, and supported by advertisements. You can use it for [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoreText_2 {
            get {
                return ResourceManager.GetString("StoreText_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEATURES:
        ///1. A simple and powerful design: The app opens directly on the entry screen, on the most recent meal, because that is what you&apos;ll use most. The design makes adding entries as simple and intuitive as possible.
        ///2. One tap entry with personalized suggestions: The most common food items can immediately be selected. Starting on the second day, your recent items are suggested because you may eat the same food frequently.
        ///3. Logging in is not needed: No personal data or contact information is required [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoreText_3 {
            get {
                return ResourceManager.GetString("StoreText_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREMIUM FEATURES:
        ///1. No more advertisement.
        ///2. A much larger food database.
        ///3. The ability to e-mail yourself a copy of the dairy.
        ///4. More configuration options, including the ability to enter up to 8 separate meals a day..
        /// </summary>
        internal static string StoreText_4 {
            get {
                return ResourceManager.GetString("StoreText_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download now because you will love using it..
        /// </summary>
        internal static string StoreText_5 {
            get {
                return ResourceManager.GetString("StoreText_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a picture.
        /// </summary>
        internal static string TakeAPicture {
            get {
                return ResourceManager.GetString("TakeAPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total2 {
            get {
                return ResourceManager.GetString("Total2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your trial is now expired. You can still view your journal, but you can&apos;t add new entries. Choose OK to unlock the full version..
        /// </summary>
        internal static string TrialExpiredBody {
            get {
                return ResourceManager.GetString("TrialExpiredBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial period expired, unlock?.
        /// </summary>
        internal static string TrialExpiredTitle {
            get {
                return ResourceManager.GetString("TrialExpiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centiliter.
        /// </summary>
        internal static string Unit_Centiliter {
            get {
                return ResourceManager.GetString("Unit_Centiliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cup.
        /// </summary>
        internal static string Unit_Cup {
            get {
                return ResourceManager.GetString("Unit_Cup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deciliter.
        /// </summary>
        internal static string Unit_Deciliter {
            get {
                return ResourceManager.GetString("Unit_Deciliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluid ounce.
        /// </summary>
        internal static string Unit_FluidOunce {
            get {
                return ResourceManager.GetString("Unit_FluidOunce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallon.
        /// </summary>
        internal static string Unit_Gallon {
            get {
                return ResourceManager.GetString("Unit_Gallon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gram.
        /// </summary>
        internal static string Unit_Gram {
            get {
                return ResourceManager.GetString("Unit_Gram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilogram.
        /// </summary>
        internal static string Unit_Kilogram {
            get {
                return ResourceManager.GetString("Unit_Kilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liter.
        /// </summary>
        internal static string Unit_Liter {
            get {
                return ResourceManager.GetString("Unit_Liter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliliter.
        /// </summary>
        internal static string Unit_Milliliter {
            get {
                return ResourceManager.GetString("Unit_Milliliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ounce.
        /// </summary>
        internal static string Unit_Ounce {
            get {
                return ResourceManager.GetString("Unit_Ounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pint.
        /// </summary>
        internal static string Unit_Pint {
            get {
                return ResourceManager.GetString("Unit_Pint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pound.
        /// </summary>
        internal static string Unit_Pound {
            get {
                return ResourceManager.GetString("Unit_Pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quart.
        /// </summary>
        internal static string Unit_Quart {
            get {
                return ResourceManager.GetString("Unit_Quart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablespoon.
        /// </summary>
        internal static string Unit_Tablespoon {
            get {
                return ResourceManager.GetString("Unit_Tablespoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaspoon.
        /// </summary>
        internal static string Unit_Teaspoon {
            get {
                return ResourceManager.GetString("Unit_Teaspoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centiliters.
        /// </summary>
        internal static string Units_Centiliter {
            get {
                return ResourceManager.GetString("Units_Centiliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cups.
        /// </summary>
        internal static string Units_Cup {
            get {
                return ResourceManager.GetString("Units_Cup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deciliters.
        /// </summary>
        internal static string Units_Deciliter {
            get {
                return ResourceManager.GetString("Units_Deciliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluid ounces.
        /// </summary>
        internal static string Units_FluidOunce {
            get {
                return ResourceManager.GetString("Units_FluidOunce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallons.
        /// </summary>
        internal static string Units_Gallon {
            get {
                return ResourceManager.GetString("Units_Gallon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grams.
        /// </summary>
        internal static string Units_Gram {
            get {
                return ResourceManager.GetString("Units_Gram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilograms.
        /// </summary>
        internal static string Units_Kilogram {
            get {
                return ResourceManager.GetString("Units_Kilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liters.
        /// </summary>
        internal static string Units_Liter {
            get {
                return ResourceManager.GetString("Units_Liter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliliters.
        /// </summary>
        internal static string Units_Milliliter {
            get {
                return ResourceManager.GetString("Units_Milliliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ounces.
        /// </summary>
        internal static string Units_Ounce {
            get {
                return ResourceManager.GetString("Units_Ounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pints.
        /// </summary>
        internal static string Units_Pint {
            get {
                return ResourceManager.GetString("Units_Pint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pounds.
        /// </summary>
        internal static string Units_Pound {
            get {
                return ResourceManager.GetString("Units_Pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarts.
        /// </summary>
        internal static string Units_Quart {
            get {
                return ResourceManager.GetString("Units_Quart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablespoons.
        /// </summary>
        internal static string Units_Tablespoon {
            get {
                return ResourceManager.GetString("Units_Tablespoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaspoons.
        /// </summary>
        internal static string Units_Teaspoon {
            get {
                return ResourceManager.GetString("Units_Teaspoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for trying the Food Diary. You have {0} trial days remaining. Press OK to unlock the app..
        /// </summary>
        internal static string UnlockFullBody {
            get {
                return ResourceManager.GetString("UnlockFullBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock now?.
        /// </summary>
        internal static string UnlockFullTitle {
            get {
                return ResourceManager.GetString("UnlockFullTitle", resourceCulture);
            }
        }
    }
}
