// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace FoodDiary2
{
	public partial class ECSlidingViewController : UIViewController
	{
		public ECSlidingViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
