// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace FoodDiary2.iOS.Controller
{
	public partial class FDFilteredReportVC : UIViewController
	{
		public FDFilteredReportVC (IntPtr handle) : base (handle)
		{
		}
	}
}
