// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace FoodDiary2.iOS.Controller
{
	public partial class FDMenuVC : UIViewController
	{
		public FDMenuVC (IntPtr handle) : base (handle)
		{
		}
	}
}
