// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace FoodDiary.iOS
{
	public partial class FDNewItemVC : UIViewController
	{
		public FDNewItemVC (IntPtr handle) : base (handle)
		{
		}
	}
}
