//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodJournalServiceWebRole.FoodJournalService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageQueue
    {
        public int Id { get; set; }
        public string MessageType { get; set; }
        public string AppInstance { get; set; }
        public bool IsServerIncoming { get; set; }
        public string Message { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Processed { get; set; }
        public string ClientKey { get; set; }
        public string Culture { get; set; }
        public string Version { get; set; }
    }
}
